
package Telas;

import java.awt.Toolkit;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago, Anderson and Hudson | Software Engineers at FATESG Senai
 */

public class TelaJogoPrincipal extends javax.swing.JFrame {

    
    int [][]jogoMatriz = new int [3][3]; //matriz do jogo
    int vezJogador = 1 ; // 1-> Jogador Xis , 2-> Jogador O bolinha
    int campeao = 3;  // define o vencedor, segue a mesma lógica do vezJogada
    int jogadas = 0; // vai contar o numero de jogadas na partida atual
    int rodada = 0; // conta a rodada, qual é a partida
    
    ImageIcon imgX = new ImageIcon(Objects.requireNonNull(getClass().getResource("imgX.png")));
    ImageIcon imgO = new ImageIcon(getClass().getResource("imgO.png"));
    ImageIcon imgPlacar = new ImageIcon(getClass().getResource("placar.png"));
    ImageIcon imgVS = new ImageIcon(getClass().getResource("vsIcon.png"));
    ImageIcon imgWinner = new ImageIcon(getClass().getResource("campeao.png"));
    
    String nomePlayerX = ""; // vai receber o nome do Player X;
    String nomePlayerO = ""; // vai receber o nome do Player O;
    
    // controle de cliques dos botoes do jogo
    boolean click00 = false;
    boolean click01 = false;
    boolean click02 = false;

    boolean click10 = false;
    boolean click11 = false;
    boolean click12 = false;

    boolean click20 = false;
    boolean click21 = false;
    boolean click22 = false;
    
    //funcao para resetar os botoes do jogo
    public void resetBtn(){
        click00 = false;
        click01 = false;
        click02 = false;

        click10 = false; 
        click11 = false;
        click12 = false;

        click20 = false;
        click21 = false;
        click22 = false;
    }
            
    /**
     * Creates new form Tela1
     */
    public TelaJogoPrincipal() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
        initComponents();
        nomes(); //chamar a função para nomear os jogadores
        telaVezJogador.setText(nomePlayerX);
        this.setLocationRelativeTo(null);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ButtonProxPartida = new javax.swing.JButton();
        ButtonResFinal = new javax.swing.JButton();
        bgTable = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Pos00 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Pos01 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Pos02 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Pos11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Pos12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Pos10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Pos20 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Pos21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Pos22 = new javax.swing.JLabel();
        telaVezJogador = new javax.swing.JLabel();
        telaRodada = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xtreme Game Old Gives");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Vez do Jogador");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rodada");

        ButtonProxPartida.setBackground(new java.awt.Color(51, 255, 51));
        ButtonProxPartida.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ButtonProxPartida.setForeground(new java.awt.Color(0, 51, 0));
        ButtonProxPartida.setText("REINICIAR RODADA");
        ButtonProxPartida.setBorder(null);
        ButtonProxPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonProxPartidaActionPerformed(evt);
            }
        });

        ButtonResFinal.setBackground(new java.awt.Color(0, 0, 0));
        ButtonResFinal.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        ButtonResFinal.setForeground(new java.awt.Color(102, 255, 102));
        ButtonResFinal.setText("RESULTADO PARCIAL");
        ButtonResFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonResFinalMouseClicked(evt);
            }
        });
        ButtonResFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResFinalActionPerformed(evt);
            }
        });

        bgTable.setBackground(new java.awt.Color(0, 255, 0));
        bgTable.setPreferredSize(new java.awt.Dimension(500, 500));
        bgTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos00MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos01MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos01, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos01, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos02MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos02, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos02, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos11, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos11, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos12, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos12, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos10, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos10, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos20, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos20, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos21, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos21, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(160, 160));

        Pos22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pos22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos22, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pos22, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        bgTable.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        telaVezJogador.setFont(new java.awt.Font("Segoe UI Black", 0, 20)); // NOI18N
        telaVezJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        telaRodada.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        telaRodada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telaRodada.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ButtonResFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addComponent(ButtonProxPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telaVezJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(telaRodada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(bgTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaVezJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telaRodada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonProxPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonResFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(bgTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //esta função irá ser chamada caso o jogo termine e serve para transferir dados para outra tela/classe e fechar a tela
    
    public void fecharTela() {
        
        dispose();
        telaResultados result = new telaResultados();
        result.setVisible(true);
    }
    
    
    public void resetarTela() {
        //limpa os botoes da partida
        Pos00.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos01.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos02.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos20.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos21.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        Pos22.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));

        //limpar posicao da matriz
        for (int l = 0; l < 3; l++) {
            for (int c = 0; c < 3; c++) {
                jogoMatriz[l][c] = 0; // o numero 0 não identifica ninguem, ou seja, a matriz principal do jogo reseta
            }
        }
        
        /*
        vezJogador = 1;
        telaVezJogador.setText(nomePlayerX); // retorna para o jogador X
        */
        
        jogadas = 0;
        campeao = 0;

        String rodadas = rodada + 1 + "";
        telaRodada.setText(rodadas);

        resetBtn();  // chama essa função para resetar a lógica dos botões, para que possibilite o clique
    }
    
    
    //deu velha na partida
    public void deuVelha() {
        if (rodada <= 4) {
            String saida = "";
            String txtRodada = "";

            saida += "Deu Empate! os dois jogadores recebem 2 pontos cada!";

            //acrescentar os pontos a cada nesse caso de empate
            if (rodada >= 1) {
                telaResultados.A[rodada][0] = telaResultados.A[rodada - 1][0] + 2;
                telaResultados.A[rodada][1] = telaResultados.A[rodada - 1][1] + 2;
            } else {
                telaResultados.A[0][0] = 2;
                telaResultados.A[0][1] = 2;
            }

            JOptionPane.showMessageDialog(null,saida,"EMPATE!",0,imgVS);

            jogadas = 0;
            campeao = 0;

            rodada += 1; // soma-se mais um na rodada, contagem da rodada, pois deu empate

            txtRodada += rodada + 1;
            telaRodada.setText(txtRodada); //imprime na tela a próxima rodada

            resetarTela();
            
            if (rodada == 5) {
                JOptionPane.showMessageDialog(null,"FIM DE JOGO!\nVAMOS PARA OS RESULTADOS!","GG! FIM DE JOGO!",0,imgWinner);

                //fecha a tela do game principal
                
                fecharTela();
                
            } 
            
        }
    }
    
    

    
    public void btnImprimirTela() { //funcão para o mostrar o RESULTADO PARCIAL do game
        String res = "";
        res = "";
        res += nomePlayerX +"  vs.  "+nomePlayerO+"\n\n";
        for (int i = 0; i < rodada; i++) {
            res += + telaResultados.A[i][0] + "    |    "  + telaResultados.A[i][1] + "\n";
        }
        JOptionPane.showMessageDialog(null,res,"PLACAR ATUAL",0,imgPlacar);
    }
    
    
    // Acrescenta os pontos do campeao da rodada na matriz resultados
    public void campeao(){
        
        if (rodada <= 4) {
            campeao = vezJogador;

            String mostraCampeao = "";     
            
            mostraCampeao = campeao == 1 ? nomePlayerX : nomePlayerO;

            String txtRodada = "";

            txtRodada += rodada + 1;
            telaRodada.setText(txtRodada);

            //armazenar resultados do vencedor, aqui  é maior que 1 porque se rodada for 1 quer dizer que a matriz ainda está na primeira posição, posiçao ZERO
            //menor igual a 4 é apenas para "proteger" a integridade da matriz resultados, para que não tenha problema de ArrayIndexOutOfBoundsException
            if (rodada >= 1 && rodada <= 4) {
                switch (campeao) {
                    case 1:
                        telaResultados.A[rodada][0] = telaResultados.A[rodada - 1][0] + 5; // soma-se a rodada anterior com a pontuação vencida da rodada
                        telaResultados.A[rodada][1] = telaResultados.A[rodada - 1][1]; // 
                        break;
                    case 2:
                        telaResultados.A[rodada][1] = telaResultados.A[rodada - 1][1] + 5;
                        telaResultados.A[rodada][0] = telaResultados.A[rodada - 1][0];
                        break;
                }
            }

            if (rodada == 0) {
                switch (campeao) {
                    case 1:
                        telaResultados.A[0][0] = 5;
                        break;
                    case 2:
                        telaResultados.A[0][1] = 5;
                        break;
                }
            }

            rodada += 1; // soma-se mais um na rodada, contagem da rodada

            // comando que mostra na tela usando um pop-up o vencedor da partida;
            if (campeao == 1) {
                JOptionPane.showMessageDialog(null,mostraCampeao,"Vencedor da Partida",0,imgX);
            } else {
                JOptionPane.showMessageDialog(null,mostraCampeao,"Vencedor da Partida",0,imgO);
            }
            

            campeao = 0;

            resetarTela(); // limpa a tela, pois já achou um vencedor
            
            if (rodada == 5) {
                JOptionPane.showMessageDialog(null,"FIM DE JOGO!\nVAMOS PARA OS RESULTADOS!","GG! FIM DE JOGO!",0,imgWinner);
                
                //fecha a tela do game principal
                fecharTela();
            }
        } 
    }
    
    
    // onde vai acontecer toda a lógica para calcular o vencedor da partida
    public void DefinirVencedorRodada(){         
        
        //loop de verificacao em linha e coluna
        for (int l = 0; l < 3; l++) {

            //verificacao em linha
            if (jogoMatriz[l][0] == vezJogador && jogoMatriz[l][1] == vezJogador && jogoMatriz[l][2] == vezJogador) {
                campeao();
            }

            //verificacao em coluna
            if (jogoMatriz[0][l] == vezJogador && jogoMatriz[1][l] == vezJogador && jogoMatriz[2][l] == vezJogador) {
                campeao();
            }
        }

        //verificacao em diagonal principal
        if (jogoMatriz[0][0] == vezJogador && jogoMatriz[1][1] == vezJogador && jogoMatriz[2][2] == vezJogador) {
            campeao();
        }

        //verificando em diagonal secundária
        if (jogoMatriz[0][2] == vezJogador && jogoMatriz[1][1] == vezJogador && jogoMatriz[2][0] == vezJogador) {
            campeao();
        }

        jogadas += 1; // se não teve campeão significa que a partida continua

        // verifica a vez e faz a troca na tela pro próximo jogador, alternando em X e O
        if (vezJogador == 1) {
            telaVezJogador.setText(nomePlayerO); //imprime na tela de qual jogador é a vez
            vezJogador = 2;
        } else {
            telaVezJogador.setText(nomePlayerX); //imprime na tela de qual jogador é a vez
            vezJogador = 1;
        }

        if (jogadas >= 9) {
            deuVelha(); // se caso o numero de jogadas for maior, significa que a partida velhou
        }

        campeao = 0;
        
        
    }
    
    
    private void ButtonResFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResFinalActionPerformed
        btnImprimirTela();
    }//GEN-LAST:event_ButtonResFinalActionPerformed

    
    private void ButtonProxPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonProxPartidaActionPerformed
        resetarTela();
    }//GEN-LAST:event_ButtonProxPartidaActionPerformed

    private void ButtonResFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonResFinalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonResFinalMouseClicked

    
    
    private void Pos00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos00MouseClicked
        if (click00 != true) {
            if (vezJogador == 1){
                Pos00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            
            jogoMatriz[0][0] = vezJogador;
            click00 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos00MouseClicked

    
    private void Pos01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos01MouseClicked
        if (click01 != true) {
            if (vezJogador == 1){
                Pos01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            
            jogoMatriz[0][1] = vezJogador;
            click01 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos01MouseClicked

    private void Pos02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos02MouseClicked
        if (click02 != true) {
            if (vezJogador == 1) {
                Pos02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[0][2] = vezJogador;
            click02 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos02MouseClicked

    private void Pos10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos10MouseClicked
        if (click10 != true) {
            if (vezJogador == 1) {
                Pos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[1][0] = vezJogador;
            click10 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos10MouseClicked

    private void Pos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos11MouseClicked
        if (click11 != true) {
            if (vezJogador == 1) {
                Pos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[1][1] = vezJogador;
            click11 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos11MouseClicked

    private void Pos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos12MouseClicked
        if (click12 != true) {
            if (vezJogador == 1) {
                Pos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[1][2] = vezJogador;
            click12 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos12MouseClicked

    private void Pos20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos20MouseClicked
        if (click20 != true) {
            if (vezJogador == 1) {
                Pos20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[2][0] = vezJogador;
            click20 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos20MouseClicked

    private void Pos21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos21MouseClicked
        if (click21 != true) {
            if (vezJogador == 1) {
                Pos21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[2][1] = vezJogador;
            click21 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos21MouseClicked

    private void Pos22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pos22MouseClicked
        if (click22 != true) {
            if (vezJogador == 1) {
                Pos22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/X.png")));
            } else {
                Pos22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/O.png")));
            }
            jogoMatriz[2][2] = vezJogador;
            click22 = true;
            DefinirVencedorRodada();
        }
    }//GEN-LAST:event_Pos22MouseClicked

    private void nomes(){
        nomePlayerX = (String)(JOptionPane.showInputDialog(null,"Qual seu nome?","JOGADOR X",0,imgX,null,""));
        if (nomePlayerX.equals("")) nomePlayerX = "Jogador X";
        
        nomePlayerO = (String)(JOptionPane.showInputDialog(null,"Qual seu nome?","JOGADOR O",0,imgO,null,""));
        if (nomePlayerO.equals("")) nomePlayerO = "Jogador O";
        
        telaResultados.nomeJogadorX = nomePlayerX ;
        telaResultados.nomeJogadorO = nomePlayerO ;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /// 
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoPrincipal().setVisible(true);
            }
        });
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonProxPartida;
    private javax.swing.JButton ButtonResFinal;
    private javax.swing.JLabel Pos00;
    private javax.swing.JLabel Pos01;
    private javax.swing.JLabel Pos02;
    private javax.swing.JLabel Pos10;
    private javax.swing.JLabel Pos11;
    private javax.swing.JLabel Pos12;
    private javax.swing.JLabel Pos20;
    private javax.swing.JLabel Pos21;
    private javax.swing.JLabel Pos22;
    private javax.swing.JPanel bgTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel telaRodada;
    private javax.swing.JLabel telaVezJogador;
    // End of variables declaration//GEN-END:variables
    
}
