
package Telas;

/**
 *
 * @author Thiago, Anderson and Hudson | Software Engineers at FATESG Senai
 */

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class telaResultados extends javax.swing.JFrame {
    
    public static String nomeJogadorX = "JOGADOR X";
    public static String nomeJogadorO = "JOGADOR O";
    
    public static int [][]A = new int [5][2]; // matriz A, usada também para receber o placar da matriz Resultados
    public static int [][]B = new int [5][2]; // Matriz B irá receber os valores invertidos da matriz A
    int [][]C = new int [2][5]; // Matriz C irá receber os valores transpostos da matriz A
    int [][]D = new int [5][2]; // Matriz D irá receber a soma das matrizes A e B
    int [][]E = new int [5][2]; // Matriz E irá receber a subtração das matrizes A e B
    int [][]F = new int [5][2]; // Matriz F irá receber a multiplicação das matrizes A e C
    
    //declaracao de icones no código
    ImageIcon imgBin = new ImageIcon(getClass().getResource("binario.png"));
    ImageIcon imgOct = new ImageIcon(getClass().getResource("octal.png"));
    ImageIcon imgHexa = new ImageIcon(getClass().getResource("hexa.png"));
    ImageIcon imgTransp = new ImageIcon(getClass().getResource("transposta.png"));
    
    /**
     * Creates new form telaResultados
     */
    public telaResultados() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
        
        initComponents();  
        
        //seta os nomes dos jogadores na tela de resultados
        jLabel7.setText(nomeJogadorX);
        jLabel14.setText(nomeJogadorO);
        jLabel20.setText(nomeJogadorX);
        jLabel21.setText(nomeJogadorO);

        ImprimeMatrizResultado();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Res00 = new javax.swing.JLabel();
        Res10 = new javax.swing.JLabel();
        Res20 = new javax.swing.JLabel();
        Res30 = new javax.swing.JLabel();
        Res40 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Res01 = new javax.swing.JLabel();
        Res11 = new javax.swing.JLabel();
        Res21 = new javax.swing.JLabel();
        Res31 = new javax.swing.JLabel();
        Res41 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ResMatriz01 = new javax.swing.JLabel();
        ResMatriz11 = new javax.swing.JLabel();
        ResMatriz21 = new javax.swing.JLabel();
        ResMatriz31 = new javax.swing.JLabel();
        ResMatriz41 = new javax.swing.JLabel();
        ResMatriz00 = new javax.swing.JLabel();
        ResMatriz10 = new javax.swing.JLabel();
        ResMatriz20 = new javax.swing.JLabel();
        ResMatriz30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ResMatriz40 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnMatrizInversa = new javax.swing.JButton();
        btnBinario = new javax.swing.JButton();
        btnOctal = new javax.swing.JButton();
        btnHexa = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labelCalcResult = new javax.swing.JLabel();
        btnTransposta = new javax.swing.JButton();
        MatrizAmaisB = new javax.swing.JButton();
        MatrizAmenosB = new javax.swing.JButton();
        MatrizAvezesB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESULTADOS DO GAME");
        setPreferredSize(new java.awt.Dimension(860, 554));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESULTADOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("RODADA 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("RODADA 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("RODADA 3");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("RODADA 4");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("RODADA 5");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("JOGADOR X");

        Res00.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res00.setForeground(new java.awt.Color(0, 0, 0));
        Res00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res00.setText("99");

        Res10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res10.setForeground(new java.awt.Color(0, 0, 0));
        Res10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res10.setText("99");

        Res20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res20.setForeground(new java.awt.Color(0, 0, 0));
        Res20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res20.setText("99");

        Res30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res30.setForeground(new java.awt.Color(0, 0, 0));
        Res30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res30.setText("99");

        Res40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res40.setForeground(new java.awt.Color(0, 0, 0));
        Res40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res40.setText("99");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 0));
        jLabel14.setText("JOGADOR O");

        Res01.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res01.setForeground(new java.awt.Color(0, 0, 0));
        Res01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res01.setText("99");

        Res11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res11.setForeground(new java.awt.Color(0, 0, 0));
        Res11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res11.setText("99");

        Res21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res21.setForeground(new java.awt.Color(0, 0, 0));
        Res21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res21.setText("99");

        Res31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res31.setForeground(new java.awt.Color(0, 0, 0));
        Res31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res31.setText("99");

        Res41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res41.setForeground(new java.awt.Color(0, 0, 0));
        Res41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Res41.setText("99");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 204, 0));
        jLabel20.setText("JOGADOR X");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 0));
        jLabel21.setText("JOGADOR O");

        ResMatriz01.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz01.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz01.setText("-");

        ResMatriz11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz11.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz11.setText("-");

        ResMatriz21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz21.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz21.setText("-");

        ResMatriz31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz31.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz31.setText("-");

        ResMatriz41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz41.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz41.setText("-");

        ResMatriz00.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz00.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz00.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz00.setText("-");

        ResMatriz10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz10.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz10.setText("-");

        ResMatriz20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz20.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz20.setText("-");

        ResMatriz30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz30.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz30.setText("-");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setText("RODADA 1");

        ResMatriz40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ResMatriz40.setForeground(new java.awt.Color(0, 0, 0));
        ResMatriz40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResMatriz40.setText("-");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setText("RODADA 2");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("RODADA 3");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("RODADA 4");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("RODADA 5");

        btnMatrizInversa.setBackground(new java.awt.Color(0, 0, 0));
        btnMatrizInversa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMatrizInversa.setForeground(new java.awt.Color(102, 255, 102));
        btnMatrizInversa.setText("MATRIZ INVERSA");
        btnMatrizInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizInversaActionPerformed(evt);
            }
        });

        btnBinario.setBackground(new java.awt.Color(0, 0, 0));
        btnBinario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBinario.setForeground(new java.awt.Color(102, 255, 102));
        btnBinario.setText("BINÁRIO");
        btnBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarioActionPerformed(evt);
            }
        });

        btnOctal.setBackground(new java.awt.Color(0, 0, 0));
        btnOctal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOctal.setForeground(new java.awt.Color(102, 255, 102));
        btnOctal.setText("OCTAL");
        btnOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOctalActionPerformed(evt);
            }
        });

        btnHexa.setBackground(new java.awt.Color(0, 0, 0));
        btnHexa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHexa.setForeground(new java.awt.Color(102, 255, 102));
        btnHexa.setText("HEXADECIMAL");
        btnHexa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RESULTADOS FINAIS");

        labelCalcResult.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        labelCalcResult.setForeground(new java.awt.Color(0, 0, 0));
        labelCalcResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCalcResult.setText("RESULTADOS APÓS CALCULOS");

        btnTransposta.setBackground(new java.awt.Color(0, 0, 0));
        btnTransposta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTransposta.setForeground(new java.awt.Color(102, 255, 102));
        btnTransposta.setText("MATRIZ TRANSPOSTA");
        btnTransposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranspostaActionPerformed(evt);
            }
        });

        MatrizAmaisB.setBackground(new java.awt.Color(0, 0, 0));
        MatrizAmaisB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MatrizAmaisB.setForeground(new java.awt.Color(102, 255, 102));
        MatrizAmaisB.setText("MATRIZ A  +  B");
        MatrizAmaisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizAmaisBActionPerformed(evt);
            }
        });

        MatrizAmenosB.setBackground(new java.awt.Color(0, 0, 0));
        MatrizAmenosB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MatrizAmenosB.setForeground(new java.awt.Color(102, 255, 102));
        MatrizAmenosB.setText("MATRIZ A  -  B");
        MatrizAmenosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizAmenosBActionPerformed(evt);
            }
        });

        MatrizAvezesB.setBackground(new java.awt.Color(0, 0, 0));
        MatrizAvezesB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MatrizAvezesB.setForeground(new java.awt.Color(102, 255, 102));
        MatrizAvezesB.setText("MATRIZ A  x  C");
        MatrizAvezesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatrizAvezesBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Res10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Res20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Res30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Res40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(Res00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel7)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Res11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Res21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Res31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Res41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Res01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMatrizInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBinario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOctal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHexa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatrizAmaisB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatrizAmenosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MatrizAvezesB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelCalcResult, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel36)
                                        .addComponent(jLabel35)
                                        .addComponent(jLabel34)
                                        .addComponent(jLabel33))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ResMatriz10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ResMatriz20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ResMatriz30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ResMatriz40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel31)
                                    .addGap(18, 18, 18)
                                    .addComponent(ResMatriz00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel20)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ResMatriz11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResMatriz21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResMatriz31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResMatriz41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResMatriz01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel21))))
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCalcResult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(ResMatriz10)
                            .addGap(40, 40, 40)
                            .addComponent(ResMatriz20)
                            .addGap(40, 40, 40)
                            .addComponent(ResMatriz30)
                            .addGap(40, 40, 40)
                            .addComponent(ResMatriz40))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel31)
                                    .addComponent(ResMatriz00))
                                .addGap(40, 40, 40)
                                .addComponent(jLabel33)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel34)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel35)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel36))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ResMatriz11)
                                    .addGap(40, 40, 40)
                                    .addComponent(ResMatriz21)
                                    .addGap(40, 40, 40)
                                    .addComponent(ResMatriz31)
                                    .addGap(40, 40, 40)
                                    .addComponent(ResMatriz41))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(22, 22, 22)
                                    .addComponent(ResMatriz01)
                                    .addGap(240, 240, 240)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Res00)
                                    .addComponent(Res01)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(btnMatrizInversa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTransposta)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(MatrizAmaisB)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Res10)
                            .addComponent(Res11))
                        .addGap(2, 2, 2)
                        .addComponent(MatrizAmenosB)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Res20)
                            .addComponent(Res21)
                            .addComponent(MatrizAvezesB))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(Res30)
                                    .addComponent(Res31))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(Res40)
                                    .addComponent(Res41)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBinario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnOctal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHexa)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void ImprimeMatrizResultado(){

        Res00.setText(""+A[0][0]);
        Res01.setText(""+A[0][1]);
        Res10.setText(""+A[1][0]);
        Res11.setText(""+A[1][1]);
        Res20.setText(""+A[2][0]);
        Res21.setText(""+A[2][1]);
        Res30.setText(""+A[3][0]);
        Res31.setText(""+A[3][1]);
        Res40.setText(""+A[4][0]);
        Res41.setText(""+A[4][1]);
    }
    
    public void imprimirBtnMatrizInversa(){
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                B[l][c] = A[4-l][c];
            }
        }
        
        ResMatriz00.setText(""+B[0][0]);
        ResMatriz01.setText(""+B[0][1]);
        ResMatriz10.setText(""+B[1][0]);
        ResMatriz11.setText(""+B[1][1]);
        ResMatriz20.setText(""+B[2][0]);
        ResMatriz21.setText(""+B[2][1]);
        ResMatriz30.setText(""+B[3][0]);
        ResMatriz31.setText(""+B[3][1]);
        ResMatriz40.setText(""+B[4][0]);
        ResMatriz41.setText(""+B[4][1]);
        labelCalcResult.setText("MATRIZ B, INVERSA DE A");
    }
    
    public void matrizTransposta(){
        String saida = "";
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                C[c][l] = A[l][c];
            }
        }
        
        for (int l = 0; l < 2; l++) {
            for (int c = 0; c < 5; c++) {
                if (C[l][c] < 10) {
                    saida +="  |  0"+ C[l][c];
                } else {
                    saida +="  |  "+ C[l][c];
                }
            }
            saida += "  |\n";
        }
        
        JOptionPane.showMessageDialog(null,saida,"MATRIZ TRANSPOSTA DE A",0,imgTransp);
    }
    
    public void MatrizAmaisB() {
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                D[l][c] = A[l][c] + B[l][c];
            }
        }
        
        ResMatriz00.setText("" + D[0][0]);
        ResMatriz01.setText("" + D[0][1]);
        ResMatriz10.setText("" + D[1][0]);
        ResMatriz11.setText("" + D[1][1]);
        ResMatriz20.setText("" + D[2][0]);
        ResMatriz21.setText("" + D[2][1]);
        ResMatriz30.setText("" + D[3][0]);
        ResMatriz31.setText("" + D[3][1]);
        ResMatriz40.setText("" + D[4][0]);
        ResMatriz41.setText("" + D[4][1]);
        labelCalcResult.setText("MATRIZ D, A + B");
    }
    
    public void MatrizAmenosB() {
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                E[l][c] = A[l][c] - B[l][c];
            }
        }

        ResMatriz00.setText("" + E[0][0]);
        ResMatriz01.setText("" + E[0][1]);
        ResMatriz10.setText("" + E[1][0]);
        ResMatriz11.setText("" + E[1][1]);
        ResMatriz20.setText("" + E[2][0]);
        ResMatriz21.setText("" + E[2][1]);
        ResMatriz30.setText("" + E[3][0]);
        ResMatriz31.setText("" + E[3][1]);
        ResMatriz40.setText("" + E[4][0]);
        ResMatriz41.setText("" + E[4][1]);
        labelCalcResult.setText("MATRIZ E, A - B");
    } 
    
    public void MatrizAvezesC(){
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                C[c][l] = A[l][c];
            }
        }
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                F[l][c] = A[l][c] * C[c][l];
            }
        }
        
        ResMatriz00.setText("" + F[0][0]);
        ResMatriz01.setText("" + F[0][1]);
        ResMatriz10.setText("" + F[1][0]);
        ResMatriz11.setText("" + F[1][1]);
        ResMatriz20.setText("" + F[2][0]);
        ResMatriz21.setText("" + F[2][1]);
        ResMatriz30.setText("" + F[3][0]);
        ResMatriz31.setText("" + F[3][1]);
        ResMatriz40.setText("" + F[4][0]);
        ResMatriz41.setText("" + F[4][1]);
        
        labelCalcResult.setText("MATRIZ F, A x C");
        
    }
    
    public void calcBinario() {
        //soma da matriz A
        int soma = 0;
        int num = 0;
        int resto = 0 ;
        
        String B1 = "";
        String bin = "";
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                soma += A[l][c];
            }
        }
        
        num = soma;
        
        String saida = "SOMA DA MATRIZ: "+soma+"\nEM BINÁRIO: ";
        
        while(num!=0) {
            resto = num % 2;
            if (resto > 0) {
                bin += "1";
            } else {
                bin += "0";
            }
            num = num / 2;
        }
        
        B1 = new StringBuilder(bin).reverse().toString();
        saida += B1;
        
        JOptionPane.showMessageDialog(null,saida,"CONVERSÃO EM BINÁRIO",0,imgBin);
    }
    
    public void calcOctal() {
        //soma da matriz A
        int soma = 0;
        int resto = 0 ;
        int quo = 1;
        
        String O1 = "";
        String oct = "";
        
        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                soma += A[l][c];
            }
        }
        
        quo = soma;
        
        
        String saida = "SOMA DA MATRIZ: "+soma+"\nEM OCTAL: ";
        while(quo != 0) {
            resto = quo % 8;
            oct += "" + resto;
            quo = quo / 8;
        }
        
        O1 = new StringBuilder(oct).reverse().toString();
        saida += O1;
        
        JOptionPane.showMessageDialog(null,saida,"CONVERSÃO EM OCTAL",0,imgOct);
    }
    
    public void calcHexa() {
        //soma da matriz A
        int soma = 0;
        int resto = 0;
        int quo = 1;

        String H1 = "";
        String hexa = "";

        for (int l = 0; l < 5; l++) {
            for (int c = 0; c < 2; c++) {
                soma += A[l][c];
            }
        }
        
        quo = soma;
        
        String saida = "SOMA DA MATRIZ: "+soma+"\nEM HEXADECIMAL: ";
        while(quo != 0) {
            resto = quo % 16;
            
            switch (resto) {
                case 10: hexa += "A"; break;
                case 11: hexa += "B"; break;
                case 12: hexa += "C"; break;
                case 13: hexa += "D"; break;
                case 14: hexa += "E"; break;
                case 15: hexa += "F"; break;
                default: hexa += "" + resto;
            }
            
            quo = quo / 16;
        }
        
        H1 = new StringBuilder(hexa).reverse().toString();
        saida += H1;
        
        JOptionPane.showMessageDialog(null,saida,"CONVERSÃO EM HEXADECIMAL",0,imgHexa);
    }
    
    
    private void btnHexaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexaActionPerformed
        calcHexa();
    }//GEN-LAST:event_btnHexaActionPerformed

    private void btnOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOctalActionPerformed
        calcOctal();
    }//GEN-LAST:event_btnOctalActionPerformed

    private void btnBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarioActionPerformed
        calcBinario();
    }//GEN-LAST:event_btnBinarioActionPerformed

    private void btnMatrizInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizInversaActionPerformed
        imprimirBtnMatrizInversa();
    }//GEN-LAST:event_btnMatrizInversaActionPerformed

    private void btnTranspostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranspostaActionPerformed
        matrizTransposta();
    }//GEN-LAST:event_btnTranspostaActionPerformed

    private void MatrizAmaisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizAmaisBActionPerformed
        MatrizAmaisB();
    }//GEN-LAST:event_MatrizAmaisBActionPerformed

    private void MatrizAmenosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizAmenosBActionPerformed
        MatrizAmenosB();
    }//GEN-LAST:event_MatrizAmenosBActionPerformed

    private void MatrizAvezesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatrizAvezesBActionPerformed
        MatrizAvezesC();
    }//GEN-LAST:event_MatrizAvezesBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MatrizAmaisB;
    private javax.swing.JButton MatrizAmenosB;
    private javax.swing.JButton MatrizAvezesB;
    private javax.swing.JLabel Res00;
    private javax.swing.JLabel Res01;
    private javax.swing.JLabel Res10;
    private javax.swing.JLabel Res11;
    private javax.swing.JLabel Res20;
    private javax.swing.JLabel Res21;
    private javax.swing.JLabel Res30;
    private javax.swing.JLabel Res31;
    private javax.swing.JLabel Res40;
    private javax.swing.JLabel Res41;
    private javax.swing.JLabel ResMatriz00;
    private javax.swing.JLabel ResMatriz01;
    private javax.swing.JLabel ResMatriz10;
    private javax.swing.JLabel ResMatriz11;
    private javax.swing.JLabel ResMatriz20;
    private javax.swing.JLabel ResMatriz21;
    private javax.swing.JLabel ResMatriz30;
    private javax.swing.JLabel ResMatriz31;
    private javax.swing.JLabel ResMatriz40;
    private javax.swing.JLabel ResMatriz41;
    private javax.swing.JButton btnBinario;
    private javax.swing.JButton btnHexa;
    private javax.swing.JButton btnMatrizInversa;
    private javax.swing.JButton btnOctal;
    private javax.swing.JButton btnTransposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCalcResult;
    // End of variables declaration//GEN-END:variables
}
